### ISSUE TITLE
Could you  please draft releases

### ISSUE THREAD

**Issue by diomed** [icons8/Lunacy#9]
for easier download from github

**Comment by alexdevero** [comment]
It would also help with updating especially since the app itself doesn't offer option to update.

**Comment by gritsenko** [comment]
> It would also help with updating especially since the app itself doesn't offer option to update.
Actually it does (for standalone version, windows store version updated automatically)
![image](https://user-images.githubusercontent.com/2227312/41713995-97644472-7557-11e8-8ac8-690ff56dc6e2.png)

**Comment by alexdevero** [comment]
@gritsenko thank you. So it is probably issue of firewall. Can you add "Check for updates" button or something like to do a manual check?

**Comment by gritsenko** [comment]
@alexdevero nice idea, thanks!

**Comment by gritsenko** [comment]
@diomed 
> for easier download from github

Do you mean something like this? 
https://github.com/icons8/Lunacy/releases/tag/untagged-d546813d5244ec1d0054

**Comment by alexdevero** [comment]
@gritsenko this is great! Thanks. Now, I can use RSS feed reader to check release channel (releases.atom).

**Comment by gritsenko** [comment]
@alexdevero cool) By the way, why not to use windows store version? :-)

**Comment by diomed** [comment]
thank you

**Comment by alexdevero** [comment]
@gritsenko I'm using the portable version.
